export { List } from './list/list.component'
export { RandomRate } from './random-rate/random-rate.component'
export { MusicCard } from './music-card/music-card.component'
export { Stars } from './stars/stars.component'
export { Main } from './main/main.component'
